package enterprises.orbital.impl.evexmlapi.unittest.test;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.URLEncoder;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Iterator;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * This class generates test data for the server API unit tests. We don't ship test data with the unit tests because it contains sensitive corp information. So
 * instead we provide a tool for generating test data yourself. We wouldn't have to do this if the various API web sites provided accurate test data but they
 * usually don't. The test data is generated by calling the EVE API directly and saving the resulting file as test data. The unit tests work by using the server
 * API to parse the response files, then traversing the resulting object to generate raw XML again. An XML diff tool then compares the two files and passes the
 * test if they are "similar", meaning they contain the same elements with the same contents but not necessarily in the same order.
 * 
 * To generate test data you need to specify a character keyID, a character vCode, a corporation keyID, a corporation vCode, and characterID to use for
 * character information queries, and a characterID to use for corporation queries. The results are stored in the "testdata" directory.
 */
public class GenerateTestData {

  protected static String       charKeyID      = null;
  protected static String       charVCode      = null;
  protected static String       charID         = null;
  protected static String       corpKeyID      = null;
  protected static String       corpVCode      = null;
  protected static String       corpID         = null;
  protected static String       fCharKeyID     = null;
  protected static String       fCharVCode     = null;
  protected static String       fCharID        = null;
  protected static List<String> nameLookupList = null;
  protected static List<Long>   idLookupList   = null;
  protected static String       serverURL      = "https://api.eveonline.com";

  protected static String usage() {
    StringBuilder help = new StringBuilder();
    help.append("java GenerateTestData -char keyID:vCode:ID -corp keyID:vCode:ID [-a] [-c] [-b] [-e] [-m] [-n names...] [-i ids...] [-fchar keyID:vCode:ID] [-u URL]\n");
    help.append("  -char <creds>    Character API credentials\n");
    help.append("  -corp <creds>    Corporation API credentials\n");
    help.append("  -a               Retrieve account level data\n");
    help.append("  -c               Retrieve character level data\n");
    help.append("  -b               Retrieve corporation level data\n");
    help.append("  -e               Retrieve Eve reference data\n");
    help.append("  -m               Retrieve map reference data\n");
    help.append("  -n               Comma separated list of names for ID lookup\n");
    help.append("  -i               Comma separated list of ids for name lookup\n");
    help.append("  -fchar <creds>   Optional FacWar credentials for character FacWar stats\n");
    help.append("  -u <url>         Set the EVE API server URL (defaults to https://api.eveonline.com)");

    return help.toString();
  }

  public static void main(String[] argv) throws Exception {
    boolean getAccountInfo = false;
    boolean getCharacterInfo = false;
    boolean getCorporationInfo = false;
    boolean getEveInfo = false;
    boolean getMapInfo = false;
    int i = 0;
    try {
      while (i < argv.length) {
        if (argv[i].equals("-a")) {
          getAccountInfo = true;
          i++;
        } else if (argv[i].equals("-n")) {
          nameLookupList = new ArrayList<String>();
          i++;
          nameLookupList.addAll(Arrays.asList(argv[i].split(",")));
          i++;
        } else if (argv[i].equals("-i")) {
          idLookupList = new ArrayList<Long>();
          i++;
          for (String id : argv[i].split(",")) {
            idLookupList.add(Long.valueOf(id));
          }
          i++;
        } else if (argv[i].equals("-c")) {
          getCharacterInfo = true;
          i++;
        } else if (argv[i].equals("-b")) {
          getCorporationInfo = true;
          i++;
        } else if (argv[i].equals("-e")) {
          getEveInfo = true;
          i++;
        } else if (argv[i].equals("-m")) {
          getMapInfo = true;
          i++;
        } else if (argv[i].equals("-char")) {
          i++;
          String[] args = argv[i].split(":");
          charKeyID = args[0];
          charVCode = args[1];
          charID = args[2];
          i++;
        } else if (argv[i].equals("-fchar")) {
          i++;
          String[] args = argv[i].split(":");
          fCharKeyID = args[0];
          fCharVCode = args[1];
          fCharID = args[2];
          i++;
        } else if (argv[i].equals("-corp")) {
          i++;
          String[] args = argv[i].split(":");
          corpKeyID = args[0];
          corpVCode = args[1];
          corpID = args[2];
          i++;
        } else if (argv[i].equals("-u")) {
          i++;
          serverURL = argv[i];
          i++;
        } else {
          System.err.println("Unrecognized argument: " + argv[i]);
          System.err.println(usage());
          System.exit(1);
        }
      }
    } catch (ArrayIndexOutOfBoundsException e) {
      System.err.println(usage());
      System.exit(1);
    }

    if (getAccountInfo) getAccountTestData();
    if (getCharacterInfo) getCharTestData();
    if (getCorporationInfo) getCorpTestData();
    if (getEveInfo) getEveTestData();
    if (getMapInfo) getMapTestData();

    System.exit(0);
  }

  protected static void storeTestData(String location, String data) throws IOException {
    FileWriter output = new FileWriter(location);
    output.write(data);
    output.close();
  }

  protected static void retrieveAndStoreData(String baseURL, String location, String... args) throws IOException {
    baseURL = serverURL + baseURL;
    System.out.print("Retrieving " + baseURL + " to " + location + "...");

    // Skip if there already exists a file.
    File existingCheck = new File(location);
    if (existingCheck.exists() && existingCheck.isFile()) {
      System.out.println("skipped (exists)");
      return;
    }

    String target = baseURL;
    if (args.length == 1) {
      target += '?' + args[0];
    } else if (args.length > 1) {
      target += Arrays.toString(args).replace('[', '?').replace(',', '&').replace(" ", "").replace("]", "");
    }
    URL getter = new URL(target);
    BufferedReader dataIn = new BufferedReader(new InputStreamReader(getter.openStream()));
    String next = dataIn.readLine();
    StringBuilder result = new StringBuilder();
    while (next != null) {
      result.append(next).append('\n');
      next = dataIn.readLine();
    }
    dataIn.close();
    storeTestData(location, result.toString());
    System.out.println("done");
  }

  public static void getAccountTestData() throws IOException {
    String credentials = "keyID=" + charKeyID + "&vCode=" + charVCode;

    retrieveAndStoreData(ApiTestConnector.ACCT_CHARACTERS_URI, ApiTestConnector.ACCT_CHARACTERS_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.ACCT_ACCOUNT_STATUS_URI, ApiTestConnector.ACCT_ACCOUNT_STATUS_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.ACCT_API_KEY_INFO_URI, ApiTestConnector.ACCT_API_KEY_INFO_CTL, credentials);
  }

  public static void getCharCalendarEventAttendees(String credentials) throws IOException {
    // Get CalendarEventAttendees. This only works if we have a recently
    // requested UpcomingCalendarEvents. Look at that file and pull out
    // all the event IDs to assemble a request.
    BufferedReader scanner = new BufferedReader(new FileReader(ApiTestConnector.CHAR_UPCOMING_CALENDAR_EVENTS_CTL));
    String nextLine = scanner.readLine();
    List<Long> ids = new ArrayList<Long>();
    Pattern matcher = Pattern.compile("eventID\\=\"([0-9]+)\"");
    while (nextLine != null) {
      Matcher check = matcher.matcher(nextLine);
      while (check.find()) {
        long nextID = Long.valueOf(check.group(1));
        ids.add(nextID);
      }
      nextLine = scanner.readLine();
    }

    String ceaCredentials = credentials + "&eventIDs=";
    for (Iterator<Long> adder = ids.iterator(); adder.hasNext();) {
      ceaCredentials += String.valueOf(adder.next());
      if (adder.hasNext()) ceaCredentials += ",";
    }

    retrieveAndStoreData(ApiTestConnector.CHAR_CALENDAR_EVENT_ATTENDEES_URI, ApiTestConnector.CHAR_CALENDAR_EVENT_ATTENDEES_CTL, ceaCredentials);
    scanner.close();
  }

  public static void getEveNameLookup() throws IOException {
    String nameList = "names=";
    for (Iterator<String> adder = nameLookupList.iterator(); adder.hasNext();) {
      nameList += URLEncoder.encode(String.valueOf(adder.next()), "UTF-8");
      if (adder.hasNext()) nameList += ",";
    }

    retrieveAndStoreData(ApiTestConnector.EVE_CHARACTER_ID_URI, ApiTestConnector.EVE_CHARACTER_ID_CTL, nameList);
  }

  public static void getEveIDLookup() throws IOException {
    String idList = "ids=";
    for (Iterator<Long> adder = idLookupList.iterator(); adder.hasNext();) {
      idList += String.valueOf(adder.next());
      if (adder.hasNext()) idList += ",";
    }

    retrieveAndStoreData(ApiTestConnector.EVE_CHARACTER_NAME_URI, ApiTestConnector.EVE_CHARACTER_NAME_CTL, idList);
  }

  public static void getCharMailBodies(String credentials) throws IOException {
    // Get MailBodies. This only works if we have recently requested MailMessages. Look at that file and pull out all message IDs to assemble a request.
    BufferedReader scanner = new BufferedReader(new FileReader(ApiTestConnector.CHAR_MAIL_MESSAGES_CTL));
    String nextLine = scanner.readLine();
    List<Long> ids = new ArrayList<Long>();
    Pattern matcher = Pattern.compile("messageID\\=\"([0-9]+)\"");
    while (nextLine != null) {
      Matcher check = matcher.matcher(nextLine);
      while (check.find()) {
        long nextID = Long.valueOf(check.group(1));
        ids.add(nextID);
      }
      nextLine = scanner.readLine();
    }

    String ceaCredentials = credentials + "&ids=";
    for (Iterator<Long> adder = ids.iterator(); adder.hasNext();) {
      ceaCredentials += String.valueOf(adder.next());
      if (adder.hasNext()) ceaCredentials += ",";
    }
    retrieveAndStoreData(ApiTestConnector.CHAR_MAIL_BODIES_URI, ApiTestConnector.CHAR_MAIL_BODIES_CTL, ceaCredentials);
    scanner.close();
  }

  public static void getCharNotificationTexts(String credentials) throws IOException {
    // Get NotificationTexts. This only works if we have recently requested Notifications. Look at that file and pull out all notification IDs to assemble a
    // request.
    BufferedReader scanner = new BufferedReader(new FileReader(ApiTestConnector.CHAR_NOTIFICATIONS_CTL));
    String nextLine = scanner.readLine();
    List<Long> ids = new ArrayList<Long>();
    Pattern matcher = Pattern.compile("notificationID\\=\"([0-9]+)\"");
    while (nextLine != null) {
      Matcher check = matcher.matcher(nextLine);
      while (check.find()) {
        long nextID = Long.valueOf(check.group(1));
        ids.add(nextID);
      }
      nextLine = scanner.readLine();
    }

    String ceaCredentials = credentials + "&ids=";
    for (Iterator<Long> adder = ids.iterator(); adder.hasNext();) {
      ceaCredentials += String.valueOf(adder.next());
      if (adder.hasNext()) ceaCredentials += ",";
    }
    retrieveAndStoreData(ApiTestConnector.CHAR_NOTIFICATION_TEXTS_URI, ApiTestConnector.CHAR_NOTIFICATION_TEXTS_CTL, ceaCredentials);
    scanner.close();
  }

  public static void getCorpStarbaseDetail(String credentials) throws IOException {
    // Get StarbaseDetails. Requires a call to StarbaseList first in order to provide at least one itemID.
    BufferedReader scanner = new BufferedReader(new FileReader(ApiTestConnector.CORP_STARBASE_LIST_CTL));
    String nextLine = scanner.readLine();
    List<Long> ids = new ArrayList<Long>();
    Pattern matcher = Pattern.compile("itemID\\=\"([0-9]+)\"");
    while (nextLine != null) {
      Matcher check = matcher.matcher(nextLine);
      while (check.find()) {
        long nextID = Long.valueOf(check.group(1));
        ids.add(nextID);
      }
      nextLine = scanner.readLine();
    }

    String ceaCredentials = credentials;
    if (ids.size() > 0) ceaCredentials += "&itemid=" + ids.get(0);
    retrieveAndStoreData(ApiTestConnector.CORP_STARBASE_DETAIL_URI, ApiTestConnector.CORP_STARBASE_DETAIL_CTL, ceaCredentials);
    scanner.close();
  }

  public static void getCharContractItems(String credentials) throws IOException {
    // Get ContractItems. This only works if we have recently requested Contracts. Look at that file and pull out at least one contract ID to assemble a
    // request.
    BufferedReader scanner = new BufferedReader(new FileReader(ApiTestConnector.CHAR_CONTRACTS_CTL));
    String nextLine = scanner.readLine();
    List<Long> ids = new ArrayList<Long>();
    Pattern matcher = Pattern.compile("contractID\\=\"([0-9]+)\"");
    while (nextLine != null) {
      Matcher check = matcher.matcher(nextLine);
      while (check.find()) {
        long nextID = Long.valueOf(check.group(1));
        ids.add(nextID);
      }
      nextLine = scanner.readLine();
    }

    String ceaCredentials = credentials;
    if (ids.size() > 0) ceaCredentials += "&contractid=" + ids.get(0);
    retrieveAndStoreData(ApiTestConnector.CHAR_CONTRACT_ITEMS_URI, ApiTestConnector.CHAR_CONTRACT_ITEMS_CTL, ceaCredentials);
    scanner.close();
  }

  public static void getCorpContractItems(String credentials) throws IOException {
    // Get ContractItems. This only works if we have recently requested Contracts. Look at that file and pull out at least one contract ID to assemble a
    // request.
    BufferedReader scanner = new BufferedReader(new FileReader(ApiTestConnector.CORP_CONTRACTS_CTL));
    String nextLine = scanner.readLine();
    List<Long> ids = new ArrayList<Long>();
    Pattern matcher = Pattern.compile("contractID\\=\"([0-9]+)\"");
    while (nextLine != null) {
      Matcher check = matcher.matcher(nextLine);
      while (check.find()) {
        long nextID = Long.valueOf(check.group(1));
        ids.add(nextID);
      }
      nextLine = scanner.readLine();
    }

    String ceaCredentials = credentials;
    if (ids.size() > 0) ceaCredentials += "&contractid=" + ids.get(0);
    retrieveAndStoreData(ApiTestConnector.CORP_CONTRACT_ITEMS_URI, ApiTestConnector.CORP_CONTRACT_ITEMS_CTL, ceaCredentials);
    scanner.close();
  }

  public static void getCharTestData() throws IOException {
    String credentials = "keyID=" + charKeyID + "&vCode=" + charVCode + "&characterID=" + charID;
    String fcredentials = fCharKeyID != null ? "keyID=" + fCharKeyID + "&vCode=" + fCharVCode + "&characterID=" + fCharID : null;

    retrieveAndStoreData(ApiTestConnector.CHAR_ACCOUNT_BALANCE_URI, ApiTestConnector.CHAR_ACCOUNT_BALANCE_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.CHAR_ASSET_LIST_URI, ApiTestConnector.CHAR_ASSET_LIST_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.CHAR_CONTRACTS_URI, ApiTestConnector.CHAR_CONTRACTS_CTL, credentials);
    getCharContractItems(credentials);
    retrieveAndStoreData(ApiTestConnector.CHAR_CONTRACT_BIDS_URI, ApiTestConnector.CHAR_CONTRACT_BIDS_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.CHAR_INDUSTRY_JOBS_URI, ApiTestConnector.CHAR_INDUSTRY_JOBS_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.CHAR_INDUSTRY_JOBS_HISTORY_URI, ApiTestConnector.CHAR_INDUSTRY_JOBS_HISTORY_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.CHAR_KILLLOG_URI, ApiTestConnector.CHAR_KILLLOG_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.CHAR_STANDINGS_URI, ApiTestConnector.CHAR_STANDINGS_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.CHAR_CHARACTER_SHEET_URI, ApiTestConnector.CHAR_CHARACTER_SHEET_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.CHAR_UPCOMING_CALENDAR_EVENTS_URI, ApiTestConnector.CHAR_UPCOMING_CALENDAR_EVENTS_CTL, credentials);
    getCharCalendarEventAttendees(credentials);
    retrieveAndStoreData(ApiTestConnector.CHAR_CONTACT_LIST_URI, ApiTestConnector.CHAR_CONTACT_LIST_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.CHAR_CONTACT_NOTIFICATIONS_URI, ApiTestConnector.CHAR_CONTACT_NOTIFICATIONS_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.CHAR_FAC_WAR_STATS_URI, ApiTestConnector.CHAR_FAC_WAR_STATS_CTL, fcredentials != null ? fcredentials : credentials);
    retrieveAndStoreData(ApiTestConnector.CHAR_MAILING_LISTS_URI, ApiTestConnector.CHAR_MAILING_LISTS_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.CHAR_MAIL_MESSAGES_URI, ApiTestConnector.CHAR_MAIL_MESSAGES_CTL, credentials);
    getCharMailBodies(credentials);
    retrieveAndStoreData(ApiTestConnector.CHAR_MARKET_ORDERS_URI, ApiTestConnector.CHAR_MARKET_ORDERS_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.CHAR_MEDALS_URI, ApiTestConnector.CHAR_MEDALS_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.CHAR_PLANETARY_COLONIES_URI, ApiTestConnector.CHAR_PLANETARY_COLONIES_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.CHAR_PLANETARY_LINKS_URI, ApiTestConnector.CHAR_PLANETARY_LINKS_CTL, credentials + "&planetID=40215544");
    retrieveAndStoreData(ApiTestConnector.CHAR_PLANETARY_ROUTES_URI, ApiTestConnector.CHAR_PLANETARY_ROUTES_CTL, credentials + "&planetID=40215544");
    retrieveAndStoreData(ApiTestConnector.CHAR_PLANETARY_PINS_URI, ApiTestConnector.CHAR_PLANETARY_PINS_CTL, credentials + "&planetID=40215544");
    retrieveAndStoreData(ApiTestConnector.CHAR_NOTIFICATIONS_URI, ApiTestConnector.CHAR_NOTIFICATIONS_CTL, credentials);
    getCharNotificationTexts(credentials);
    retrieveAndStoreData(ApiTestConnector.CHAR_RESEARCH_URI, ApiTestConnector.CHAR_RESEARCH_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.CHAR_SKILL_IN_TRAINING_URI, ApiTestConnector.CHAR_SKILL_IN_TRAINING_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.CHAR_SKILL_QUEUE_URI, ApiTestConnector.CHAR_SKILL_QUEUE_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.CHAR_WALLET_JOURNAL_URI, ApiTestConnector.CHAR_WALLET_JOURNAL_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.CHAR_WALLET_TRANSACTIONS_URI, ApiTestConnector.CHAR_WALLET_TRANSACTIONS_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.EVE_CHARACTER_INFO_URI, ApiTestConnector.EVE_CHARACTER_INFO_CTL, credentials);
  }

  public static void getCorpTestData() throws IOException {
    String credentials = "keyID=" + corpKeyID + "&vCode=" + corpVCode + "&characterID=" + corpID;

    retrieveAndStoreData(ApiTestConnector.CORP_ACCOUNT_BALANCE_URI, ApiTestConnector.CORP_ACCOUNT_BALANCE_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.CORP_ASSET_LIST_URI, ApiTestConnector.CORP_ASSET_LIST_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.CORP_CONTRACTS_URI, ApiTestConnector.CORP_CONTRACTS_CTL, credentials);
    getCorpContractItems(credentials);
    retrieveAndStoreData(ApiTestConnector.CORP_CONTRACT_BIDS_URI, ApiTestConnector.CORP_CONTRACT_BIDS_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.CORP_INDUSTRY_JOBS_URI, ApiTestConnector.CORP_INDUSTRY_JOBS_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.CORP_INDUSTRY_JOBS_HISTORY_URI, ApiTestConnector.CORP_INDUSTRY_JOBS_HISTORY_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.CORP_KILLLOG_URI, ApiTestConnector.CORP_KILLLOG_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.CORP_STANDINGS_URI, ApiTestConnector.CORP_STANDINGS_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.CORP_CORPORATION_SHEET_URI, ApiTestConnector.CORP_CORPORATION_SHEET_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.CORP_CONTACT_LIST_URI, ApiTestConnector.CORP_CONTACT_LIST_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.CORP_FAC_WAR_STATS_URI, ApiTestConnector.CORP_FAC_WAR_STATS_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.CORP_MARKET_ORDERS_URI, ApiTestConnector.CORP_MARKET_ORDERS_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.CORP_MEDALS_URI, ApiTestConnector.CORP_MEDALS_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.CORP_WALLET_JOURNAL_URI, ApiTestConnector.CORP_WALLET_JOURNAL_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.CORP_WALLET_TRANSACTIONS_URI, ApiTestConnector.CORP_WALLET_TRANSACTIONS_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.CORP_CONTAINER_LOG_URI, ApiTestConnector.CORP_CONTAINER_LOG_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.CORP_MEMBER_MEDALS_URI, ApiTestConnector.CORP_MEMBER_MEDALS_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.CORP_MEMBER_SECURITY_URI, ApiTestConnector.CORP_MEMBER_SECURITY_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.CORP_MEMBER_SECURITY_LOG_URI, ApiTestConnector.CORP_MEMBER_SECURITY_LOG_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.CORP_MEMBER_TRACKING_URI, ApiTestConnector.CORP_MEMBER_TRACKING_CTL, credentials + "&extended=1");
    retrieveAndStoreData(ApiTestConnector.CORP_SHAREHOLDERS_URI, ApiTestConnector.CORP_SHAREHOLDERS_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.CORP_STARBASE_LIST_URI, ApiTestConnector.CORP_STARBASE_LIST_CTL, credentials);
    getCorpStarbaseDetail(credentials);
    retrieveAndStoreData(ApiTestConnector.CORP_TITLES_URI, ApiTestConnector.CORP_TITLES_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.CORP_FACILITIES_URI, ApiTestConnector.CORP_FACILITIES_CTL, credentials);
    retrieveAndStoreData(ApiTestConnector.CORP_CUSTOMS_OFFICES_URI, ApiTestConnector.CORP_CUSTOMS_OFFICES_CTL, credentials);
  }

  public static void getEveTestData() throws IOException {
    retrieveAndStoreData(ApiTestConnector.SERVER_STATUS_URI, ApiTestConnector.SERVER_STATUS_CTL);
    retrieveAndStoreData(ApiTestConnector.EVE_ALLIANCE_LIST_URI, ApiTestConnector.EVE_ALLIANCE_LIST_CTL);
    retrieveAndStoreData(ApiTestConnector.EVE_CERTIFICATE_TREE_URI, ApiTestConnector.EVE_CERTIFICATE_TREE_CTL);
    retrieveAndStoreData(ApiTestConnector.EVE_CONQ_STATION_LIST_URI, ApiTestConnector.EVE_CONQ_STATION_LIST_CTL);
    retrieveAndStoreData(ApiTestConnector.EVE_ERROR_LIST_URI, ApiTestConnector.EVE_ERROR_LIST_CTL);
    retrieveAndStoreData(ApiTestConnector.EVE_FAC_WAR_STATS_URI, ApiTestConnector.EVE_FAC_WAR_STATS_CTL);
    retrieveAndStoreData(ApiTestConnector.EVE_FAC_WAR_TOP_STATS_URI, ApiTestConnector.EVE_FAC_WAR_TOP_STATS_CTL);
    retrieveAndStoreData(ApiTestConnector.EVE_REF_TYPES_URI, ApiTestConnector.EVE_REF_TYPES_CTL);
    retrieveAndStoreData(ApiTestConnector.EVE_SKILL_TREE_URI, ApiTestConnector.EVE_SKILL_TREE_CTL);
    if (nameLookupList != null) getEveNameLookup();
    if (idLookupList != null) getEveIDLookup();
  }

  public static void getMapTestData() throws IOException {
    retrieveAndStoreData(ApiTestConnector.MAP_FAC_WAR_SYSTEMS_URI, ApiTestConnector.MAP_FAC_WAR_SYSTEMS_CTL);
    retrieveAndStoreData(ApiTestConnector.MAP_JUMPS_URI, ApiTestConnector.MAP_JUMPS_CTL);
    retrieveAndStoreData(ApiTestConnector.MAP_KILLS_URI, ApiTestConnector.MAP_KILLS_CTL);
    retrieveAndStoreData(ApiTestConnector.MAP_SOVEREIGNTY_URI, ApiTestConnector.MAP_SOVEREIGNTY_CTL);
  }

}
